version: '3.3'
 
services:
 
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
   
    ports:
      - "1433:1433"